spring:
#  http:
#    log-request-details: true
  profiles:
    active: production
logging:
  level:
    org:
      springframework:
        web: warn
    root: warn

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId:
#            clientSecret:
#          google:
#            clientId:
#            clientSecret:

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,mappings

jwt:
  signing-key-secret: A$ecretF0r$igningJWTs
  get-token-uri: /authenticate
  refresh-token-uri: /refresh
  http-request-header: Authorization
  token:
    expiration-in-seconds: 604800

springdoc:
  api-docs:
    path: /api-docs