spring:
  profiles:
    active: production
logging:
  level:
    org:
      springframework:
        web: warn
    root: warn

auth0:
  issuer: https://curena-dev.auth0.com
  api-audience: https://tasks.starter.com

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,mappings

springdoc:
  api-docs:
    path: /api-docs