spring:
  profiles:
    active: production
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId:
#            clientSecret:
#          google:
#            clientId:
#            clientSecret:

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,mappings

jwt:
  signing-key-secret:
  get-token-uri: /authenticate
  refresh-token-uri: /refresh
  http-request-header: Authorization
  token:
    expiration-in-seconds: 604800