spring:
  profiles:
    active: production
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId:
#            clientSecret:
#          google:
#            clientId:
#            clientSecret:

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,mappings