spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 89246c1301f6894ef5bd
            clientSecret: 7bbbf2ae9a1b9f3877be2aee904d51932a7d0eb9
