spring:
  profiles:
    active: test
logging:
  level:
    org:
      springframework:
        web: debug
    root: debug
jwt:
  token:
    expiration-in-seconds: 86400

auth0:
  issuer: https://curena-dev.auth0.com
  api-audience: https://tasks.starter.com
  grant-type: client_credentials
  authorization-uri: /oauth/token