spring:
  profiles:
    active: test

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: 89246c1301f6894ef5bd
#            clientSecret:
jwt:
  signing-key-secret: YmFy
  get-token-uri: /authenticate
  refresh-token-uri: /refresh
  http-request-header: Authorization
  token:
    expiration-in-seconds: 604800