spring:
  profiles:
    active: test
logging:
  level:
    org:
      springframework:
        web: debug
    root: debug
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: 89246c1301f6894ef5bd
#            clientSecret:
jwt:
  refresh-token-uri: /refresh
  token:
    expiration-in-seconds: 604800